export const BEGIN_FETCH_TODOS = "BEGIN_FETCH_TODOS";
export const SUCCESS_FETCH_TODOS = "SUCCESS_FETCH_TODOS";
export const ERROR_FETCH_TODOS = "ERROR_FETCH_TODOS";

export const BEGIN_ADD_TODOS = "BEGIN_ADD_TODOS";
export const SUCCESS_ADD_TODOS = "SUCCESS_ADD_TODOS";
export const ERROR_ADD_TODOS = "ERROR_ADD_TODOS";

export const BEGIN_EDIT_TODOS = "BEGIN_EDIT_TODOS";
export const SUCCESS_EDIT_TODOS = "SUCCESS_EDIT_TODOS";
export const ERROR_EDIT_TODOS = "ERROR_EDIT_TODOS";

export const DELETE_TODOS_BEGIN = "DELETE_TODOS_BEGIN";
export const DELETE_TODOS_SUCCESS = "DELETE_TODOS_SUCCESS";
export const DELETE_TODOS_ERROR = "DELETE_TODOS_ERROR";

export const BEGIN_FINISH_TODOS = "BEGIN_FINISH_TODOS";
export const SUCCESS_FINISH_TODOS = "SUCCESS_FINISH_TODOS";
export const ERROR_FINISH_TODOS = "ERROR_FINISH_TODOS";
